version: "3.3"
services:

  app1:
    image: mustafa91/app1:latest
    ports:
      - "7766:8080"
    container_name: app1
  
  app2:
    build: ./app2/Java-testapp
    ports:
       - "8866:8080"
    container_name: app2

  nginx:
    image: mustafa91/nginx-reverse-proxy:latest
    ports:
      - "80:80"
    container_name: project_reverse-proxy
